---
- name: Install Docker
  hosts: depolyment
  become: yes
  vars:
    username: "tommylin"
    # replace above username with yours.
  tasks:
  - name: update apt 
    ansible.builtin.apt:
      update_cache: yes
      state: latest
  - name: apt install prerequisites
    ansible.builtin.apt:
      name: 
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
      state: present
  - name: download apt key
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present
  - name: Add Docker repo to sources.list
    apt_repository:
      repo: deb https://download.docker.com/linux/debian bullseye stable
      state: present
  - name: update apt cache
    ansible.builtin.apt:
      update_cache: yes
      state: latest
  - name: install docker engine
    ansible.builtin.apt:
      name: 
        - docker-ce 
        - docker-ce-cli 
        - containerd.io 
        - docker-buildx-plugin 
        - docker-compose-plugin
      state: present
  - name: create docker group
    shell: sudo groupadd docker
    ignore_errors: true
  - name: put user to docker group
    shell: sudo usermod -a -G docker "{{username}}"
